---
title: "Introduction"
author: "Janko Thyson"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{README}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
run <- FALSE
root_dir <- paste(rep("../", 1), collapse = "")
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
knitr::opts_knit$set(root.dir = root_dir)
```

# TODO

* 20170303: flesh out introduction

# Create instance

```{r}
createInstance(of = "Testclass")
createInstance(of = "Testclass", with = letters[1:3])
createInstance(of = "Testclass", with = letters[1:3], inherits = TRUE)
createInstance(of = "Testclass", with = letters[1:3], inherits = TRUE,
  attributes = list(attr_1 = TRUE, attr_2 = "yep!"))
createInstance(of = "Testclass", with = letters[1:3], inherits = TRUE,
  attributes = list(my_attrs = list(attr_1 = TRUE, attr_2 = "yep!")))
```

# Use in S3 methods

## Create methods

```{r}
foo <- function(x, context) {
  UseMethod("foo", x)
}

foo.Testclass1 <- function(x, context = NULL) {
  UseMethod("foo.Testclass1", context)
}

foo.Testclass1.NULL <- function(x, context = NULL) {
  "Hello World!"
}

foo.Testclass1.Context1 <- function(x, context) {
  "I'm the method for context 1"
}

foo.Testclass1.Context2 <- function(x, context) {
  "I'm the method for context 2"
}
```

## Call methods

```{r}
x <- createInstance("Testclass1")
foo(x)

ctxt_1 <- createInstance("Context1")
foo(x = x, context = ctxt_1)

ctxt_2 <- createInstance("Context2")
foo(x = x, context = ctxt_2)
```

